# This is a basic workflow to help you get started with Actions

name: Build site and deploy on Khoury server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up Hugo
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.91.2'
          extended: true
          
      - name: Build
        run: hugo --minify -b "http://khoury.northeastern.edu/research/helpinghands/"
        
      - name: Remove old files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /proj/rplatt/helpinghands/.www ; ls | grep -v 'backup' | xargs -r rm -r

      - name: Transfer Files
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "public/*"
          target: "/proj/rplatt/helpinghands/.www"
          strip_components: 1
          
      - name: Generate group.html
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /proj/rplatt/helpinghands/.www ; cp index.html group.html
